# NOTE: This global dynamic plugins configuration will be overridden by config/dynamic-plugins.yaml
# To add any plugin configuration, please add it to the dynamic-plugins.yaml file instead
# global:
#   dynamic:
#     includes:
#       - 'dynamic-plugins.default.yaml'
#     plugins: []
upstream:
  backstage:
    extraAppConfig:
      - configMapRef: app-config-rhdh
        filename: app-config-rhdh.yaml
    extraEnvVarsSecrets:
      - rhdh-secrets